x-worker: &worker
  image: ghcr.io/d3vk1ng1337/rinha-backend-26-zero:91df46dfffeb4d587a413bee0d8ba670f9cf5803
  command: ["worker"]
  environment: &workerenv
    INDEX_PATH: /index/index.bin
    NPROBE: "12"
    REPAIR_MIN: "1"
    REPAIR_MAX: "4"
    BUSY_POLL_US: "0"
    EPOLL_SPIN_US: "15"
    EPOLL_IDLE_US: "80"
    MALLOC_ARENA_MAX: "1"
  volumes:
    - socks:/run/sock
  ulimits:
    nofile:
      soft: 65535
      hard: 65535

services:
  worker0:
    <<: *worker
    cpuset: "0"
    environment:
      <<: *workerenv
      CTRL: /run/sock/api0.ctrl
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 160M

  worker1:
    <<: *worker
    cpuset: "1"
    environment:
      <<: *workerenv
      CTRL: /run/sock/api1.ctrl
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 160M

  lb:
    image: ghcr.io/d3vk1ng1337/rinha-backend-26-zero:91df46dfffeb4d587a413bee0d8ba670f9cf5803
    command: ["lb"]
    cpuset: "2,3"
    environment:
      PORT: "9999"
      BACKENDS: "/run/sock/api0.ctrl,/run/sock/api1.ctrl"
    ports:
      - "9999:9999"
    volumes:
      - socks:/run/sock
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - worker0
      - worker1
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 30M

volumes:
  socks:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=10m"
